### ISSUE TITLE
Excellent network Upnp project, how to download and use it?

### ISSUE THREAD

**Issue by MeowLove** [DecentralizationSoftware/Decentralization.Software#1]
This is an excellent network upnp software, but I only saw the picture introduction of MS Store and can't download it. 
https://apps.microsoft.com/store/detail/upnp-port-mapper/9PBT9LKW4Z7B
I found the Github project, but I didn't find the executable file download. Can u provide the binary program download?

**Comment by DecentralizationSoftware** [comment]
You should be able to download it now, try again...
